### ISSUE TITLE
Use role dependencies

### ISSUE THREAD

**Issue by andersharrisson-ess** [alvistack/ansible-collection-kubernetes#1]
I think it makes sense to use role dependencies to simplify usage of the collection and conform to Ansible best practices.
Due to extensive tagging on role tasks, there is already flexibility for the users to skip roles they do not need or want to exchange for their own roles, by using `--skip-tags`.
By default, I think it would make sense to reference other roles in your collection. This makes even more sense when you look at roles like kube_node and kube_master, where you have variables named `kubelet_*` and `kubeadm_*`. This means that you implicitly expect kubelet and kubeadm to have been installed. It also breaks the variable namespace convention of only defining variables with the role name as prefix.

**Comment by hswong3i** [comment]
> I think it makes sense to use role dependencies to simplify usage of the collection and conform to Ansible best practices.
> Due to extensive tagging on role tasks, there is already flexibility for the users to skip roles they do not need or want to exchange for their own roles, by using --skip-tags.

Traditionally I tried with `meta/main.yml` and specify the roles dependency; BTW whenever I need to update it, e.g. previously a lots of roles depends on `bootstrap` + `python` but now simplified as only `python`, I will need to update both `ansible-role-requirements.yml`, `molecule/default/converge.yml` and `meta/main.yml` (OMG too complicated...); moreover, this restrict my roles running order which not my target...

>  By default, I think it would make sense to reference other roles in your collection. This makes even more sense when you look at roles like kube_node and kube_master, where you have variables named kubelet_* and kubeadm_*. This means that you implicitly expect kubelet and kubeadm to have been installed. It also breaks the variable namespace convention of only defining variables with the role name as prefix.

Most roles are already implement its variables with its own namespace, but `kube_master` and `kube_node` most likely the only exception. If all its variables prefixed with `kube_master` or `kube_node` will make everything looks very complicated. As a top predator it always required for other roles getting installed and ready correctly. I had try my best to keep everything clean and tidy, but really difficult for this two roles ;-(

**Comment by aharrisson** [comment]
Thank you for the clarifications, @hswong3i . I appreciate that you take the time to explain your thoughts and ideas.

> previously a lots of roles depends on bootstrap + python but now simplified as only python

Right, you basically have to decide on an expected, prerequisite state of the hosts. The python role makes sense. The bootstrap role is a bit weird, though. It only sets up package repos and installs packages. It's hard to see who will use these packages. They should probably rather be installed by the respective role that needs them.

> this restrict my roles running order which not my target...

I completely respect your design decision if this is what you intended. Personally I would probably have controlled the running order through dependencies instead. The only awkward situation I can think of is for `kube_node` and `kube_master`. You want their dependencies installed in the same play. I have seen that you solve this in the playbook by running multiple plays: https://github.com/alvistack/ansible-collection-kubernetes/blob/master/playbooks/kubernetes-install.yml
First one play to install the dependencies. Then one play to install master. Then one to install nodes. That is a fine way of doing it, but delegates the responsibility to the playbook. I would probably have deployed it all in the same play, and control what role is applied where through variables.

> Most roles are already implement its variables with its own namespace, but kube_master and kube_node most likely the only exception. If all its variables prefixed with kube_master or kube_node will make everything looks very complicated. As a top predator it always required for other roles getting installed and ready correctly. I had try my best to keep everything clean and tidy, but really difficult for this two roles ;-(

Yes, it's really hard to keep roles for Kubernetes clean. Everything is, sort of, coupled. So to decouple them in a sane way is difficult.
You also have `kubernetes_version` defined in a few roles (kubeadm, kubelet, kubectl), which breaks the convention. This could also easily be solved with dependencies. If we take the kubelet role as an example, it should only define `kubelet_version`. If you (for some odd reason) only wanted to install kubelet on a machine, you would define the desired version with `kubelet_version`. But if you wanted to install a kubernetes master node, you would apply `kube_master` role with `kube_master_version` defined to the version you want. In `kube_master` role's `vars/main.yml` you would then set `kubelet_version: "{{ kube_master_version }}"` and define a dependency on `kubelet` role in `meta/main.yml`.

**Comment by hswong3i** [comment]
Before answer your idea let's me share some of my learning experience with you. Since 2017 Sep I start packaging some Atlassian apps into docker container, e.g. JIRA/Confluence/Bitbucket/etc. By the end of 2017 I start learning on Kubernetes for my client's paid project. Due to my 2+ years Ansible experience (or even earlier, with experience on openstack-ansible), I kick start everything with kubespray and ceph-ansible.

Due to the lack of support of cephfs-provisioner and ingress-nginx and cert-manager from kubespray, I start contributing kubespray directly with PRs. Soon after that, I become a top-10 contributor for kubespray, just simply before 2020 March.

So why did I finally give up such contribution but starting my own one-man-band like personal-battle from sketch, in this homogeneous architecture? Simply because you can't truly reuse the individual roles from kubespray nor ceph-ansible. They are TOTALLY NOT reusable from other else Ansible project.

Wait! caph-ansible submit all its individual roles into galaxy, which looks to be following Ansible suggested best practices so how could it be NOT reusable? If you try to integrate it into kubespray, the only way is to accept it in all-or-nothing black-box style, so as like as that live within openstack-ansible.

Long story short: don't simply trust Ansible's Best Practices recommendation. World is not such ideal, roles could not always working fine with each others, unless they are design and implemented in a homogeneous design style.

> I completely respect your design decision if this is what you intended. Personally I would probably have controlled the running order through dependencies instead. The only awkward situation I can think of is for kube_node and kube_master.

Before I drop the `docker` role support (see https://github.com/alvistack/ansible-collection-kubernetes/commit/c79ab64ae514195c4d9c2743db714e58cef2b04a), this collection was supporting both `docker` and `cri_o` as CRI. Therefore how `kube_master` or `kube_node` dependencies managed in `galaxy.yml` could handle it? Shall we ALWAYS depend on `docker` in `galaxy.yml` and so manually and additionally install `cri_o` by using playbook?

> Yes, it's really hard to keep roles for Kubernetes clean. Everything is, sort of, coupled. So to decouple them in a sane way is difficult.

The reason why `kubectl`, `kubeadm` and `kubelet` sharing a abstractly shared variable `kubernetes_version` is again due to KISS principle. See https://github.com/alvistack/ansible-collection-kubernetes/blob/master/inventory/sample/group_vars/all/00-defaults.yml#L17-L23. If they are handling with it own namespace prefix, then we need to specify them into 3 lines but sync the version manually.

If you check my git commit history for each roles, you could found that I did a numbers of different try for these set of variables combination, including your suggestion. 

P.S. That's also similar reason for using `git submodule` rather than `ansible-role-requirements.yml` in collection.

P.P.S. **Was vernünftig ist, das ist wirklich; und was wirklich ist, das ist vernünftig** (see https://de.wikipedia.org/wiki/Grundlinien_der_Philosophie_des_Rechts#Epigramm, English: What is reasonable is real; that which is real is reasonable; Chinese: 凡是合理的都是現實的，凡是現實的都是合理的). If current implementation is not reasonable enough for simplifying my daily maintenance, I had already drop it in my pass `git commit`, with no delay ;-)
