### ISSUE TITLE
Allow unique role implementations

### ISSUE THREAD

**Issue by andersharrisson-ess** [alvistack/ansible-collection-kubernetes#2]
The current implementation with homogeneous roles, all sharing the same skeleton tasks has its advantages, but in some cases it makes the roles hard to understand. Some roles have tasks that does nothing, just for the sake of being homogeneous. By making the roles heterogeneous they could have more explicit log output, and be easier to maintain.
One example is the `kubectl`, where there really isn't any difference between the distros, but it still separates the tasks into distro-specific implementations and adds a lot of different `vars` files with virtually the same content.
Another example is `kubeadm`, where all distro-specific files (tasks and vars) are completely empty.

**Comment by hswong3i** [comment]
There are many latent needs to make them such homogeneous, but as a most likely one-man-band project(s) I always follow the "Keep It Simple Stupid" principle (see https://en.wikipedia.org/wiki/KISS_principle).

![image](https://user-images.githubusercontent.com/780562/80274943-affc5e80-8710-11ea-9787-5fe2f483e488.png)
(credit https://garfield.com/comic/1991/02/24)

let's review following commits:
- https://github.com/alvistack/ansible-role-bootstrap/commit/e781c6836b1a6e8b56fc63af97bde33f280baf61
- https://github.com/alvistack/ansible-role-ansible/commit/9c36fd10619402fe49a50900863a9317076c7567
- https://github.com/alvistack/ansible-role-ceph_common/commit/846a3dd9aa96595ee8682ad86211f94516b9f88b

Could you see their commit content and timing? They are totally identical, right? So how could this happened?
- First of all manually change within a single role, e.g. `ansible-role-bootstrap`
- After manually testing, create a patch file with `git diff HEAD > /tmp/patch` then `git reset HEAD && git checkout -- .` it

Now going back to one level folder above and execute follow 3-minutes-craft bash script (well, usually I will do some additional check before commit and push):
```
ls -1d ansible-role-* | while read line; do
  cd $line
  git checkout develop
  patch -p1 < /tmp/patch
  git add --all .
  git commit -am '`molecule -s default` with delegated to localhost'
  git push --all --force -u origin && git push --tags &
  cd ../
done
```

See how lazy am I... That's only works perfectly if all roles are in homogeneous design pattern ;-)

Anyway, another useful reason for create those empty-and-dummy per distro vars/tasks are restricting the run of Ansible Role only for supported OS/version. If you are running my roles for Debian 10, due to the missing of `vars/debian-10.yml` you will not able to execute it, therefore you will understand that it is not supported ;-)

**Comment by aharrisson** [comment]
Good answer. I am all for KISS as well, so understand your reasons.
I would probably have implemented it differently, for different reasons, but that is probably why there are so many open source projects out there that solves the same problems just with different implementations.

Thank you for sharing the background for the design decision. You may close the issue.
